### ISSUE TITLE
In VS2015, conditional breakpoint editor has problems

### ISSUE THREAD

**Issue by baldurk** [jaredpar/VsVim#1777]
There's some new bullshit in VS2015 that pops up a kind of bizarre in-line thing inside the code editor for changing breakpoint conditions:

![image](https://cloud.githubusercontent.com/assets/661798/14704174/aca082c4-07b3-11e6-956f-b74ee034c616.png)

This seems to interact badly with the normal text editor - even if you're in normal mode then typing into the condition box will insert text - but if you hit a command key like `.` it will perform a repeat in the text editor wherever the cursor was. You can't manually jump into insert mode with insert, and typing `i` just inserts a literal `i`. Likewise you can't yank/paste or anything as it will just insert a literal `y` or `p`.

The workaround I can find is to go into insert mode first, then open the breakpoint condition. That way at least it's consistent that characters are entered literally, not some mixed insert/normal mode.

I normally use VS2010 thankfully, so this isn't too much of a blocking issue for me, but I figured I'd let you know. I'm running VsVim 2.0.1.0 installed via the VS extension browser.

**Comment by jaredpar** [comment]
Thanks for letting me know.  I'm pretty sure I fixed this in a recent build but will verify.

**Comment by baldurk** [comment]
Apologies for the bump, but this still happens for me in 2.3.0. I just updated to VS2015 ( :cry: ) so I'm going to hit this often now.

I've dabbled in the code a little before to fix some minor issues like #1715 but given that this is more tightly integrated into VS I'm not really sure where to start, if you have some pointers of where to start looking then I can try to help.

**Comment by jaredpar** [comment]
Hmm, wonder why I'm not hitting this.  Will see if I can find a diff way to repo. 

> I've dabbled in the code a little before to fix some minor issues like #1715 but given that this is more tightly integrated into VS I'm not really sure where to start

Yeah keyboard issues are nasty, especially in the VS layer.  This is pretty much the worst case because it's mixing all the bad keyboard elements into one scenario.  😦

**Comment by baldurk** [comment]
Well, I should have been less lazy and just gotten my hands dirty in the first place. I put in some tracing to see if I could understand how it worked, and while looking at the output I noticed a difference in the existing debug trace output between typing `i` and `.` in the breakpoint condition field:

```
VsVim VisualAssistKeyProcessor::PreviewKeyDown I None 
VsVim VisualAssistKeyProcessor::KeyDown Handled = False 
VsVim VimKeyProcessor::KeyDown I None 
VsVim VimKeyProcessor::KeyDown Handled = False 
VsVim VisualAssistKeyProcessor::PreviewKeyUp I None 
VsVim VimBufferCoordinator::PreviewKeyUp I 
VsVim VimKeyProcessor::KeyUp I None 
VsVim VimKeyProcessor::KeyUp Handled = False 
VsVim VimBufferCoordinator::KeyUp I 
```

```
VsVim VisualAssistKeyProcessor::PreviewKeyDown OemPeriod None 
VsVim VisualAssistKeyProcessor::KeyDown Handled = True 
VsVim VisualAssistKeyProcessor::PreviewKeyUp OemPeriod None 
VsVim VimBufferCoordinator::PreviewKeyUp OemPeriod 
VsVim VimKeyProcessor::KeyUp OemPeriod None 
VsVim VimKeyProcessor::KeyUp Handled = False 
VsVim VimBufferCoordinator::KeyUp OemPeriod 
```

Looking at the code to see why the `VimKeyProcessor::KeyDown` wasn't getting called, I found [some special case code](https://github.com/jaredpar/VsVim/blob/master/Src/VsVimShared/Implementation/VisualAssist/VisualAssistKeyProcessor.cs#L25-L39) for handling `.` when visual assist is active.

Testing further, if I disable visual assist then I can type `.` just fine - it's only when both are enabled and this special case kicks in. Sorry about that - I should have listed my full environment including VAX, or tested without it, I just didn't expect it to be a factor :worried:.

Removing that code makes the breakpoint editor work fine, although I can now repro the issue outlined in the comment (hitting escape then `.` in rapid succession inserts a `.` instead of performing repeat). For me that's the lesser of two evils, and I have no idea how to approach fixing this, so I'll work with a local build like that for now. Hopefully this is more concrete information now though that you can work out a proper fix :).

Btw, this might be the same underlying bug as #1875 ?

**Comment by jaredpar** [comment]
Great sleuthing 😄 

Yeah that definitely seems to be the issue.  I think I need to special case this to handle the case where we are in the break point editor.  I need to look into figuring out that context. 

> Btw, this might be the same underlying bug as #1875 ?

It may be related.

**Comment by ricksladkey** [comment]
It does appear to be a duplicate of #1875 and #1971. I believe both were fixes by PR #2201.

**Comment by baldurk** [comment]
Confirmed for me, this works with 2.6.942 installed. Thanks!
